FROM serafinframework/nodejs
LABEL maintainer="Nicolas Degardin <degardin.n@gmail.com>"

USER root
RUN apk --update --no-cache add nodejs-doc nodejs-dev
RUN /opt/docker/install-devtools.sh && rm /opt/docker/install-devtools.sh
RUN sed -ri 's#^plugins=\(([^)]+)\)$#plugins=(\1 node npm gulp bower)#g' /etc/zsh/zshrc
ADD files/ssh_config /etc/ssh_config
RUN chmod 400 /etc/ssh_config

USER node
RUN echo '' > $HOME/.zshrc
RUN mkdir -p /home/node/cache && touch /home/node/cache/npm_completion
ENV ZSH_CACHE_DIR /home/node/cache
ENV PATH="/home/node/.npm/bin:$PATH"  

VOLUME ["/home/node/.ssh"]
VOLUME ["/srv"]
